"""
Ports — Interfaces that domain services depend on, not infrastructure.
"""

from typing import Protocol

from callibr_contracts.audit import AuditRecord
from callibr_contracts.persona import PersonaDefinition
from callibr_contracts.procedure import ProcedureDefinition, ProcedureExecution
from callibr_contracts.rule import RuleDefinition
from callibr_contracts.scenario import ScenarioDefinition
from callibr_contracts.simulation import ScenarioSummary, SimulationSession


from callibr_contracts.simulation import SimulationSession, SimulationMessage

class SimulationSessionStore(Protocol):
    def save(self, session: SimulationSession) -> None: ...

    def get(self, session_id: str) -> SimulationSession | None: ...

    def list(self) -> list[SimulationSession]: ...


class SimulationTurnStore(Protocol):
    def save_turns(self, session_id: str, turns: list[SimulationMessage]) -> None: ...
    def get_turns(self, session_id: str) -> list[SimulationMessage]: ...


class AuditEventStore(Protocol):
    def append(self, record: AuditRecord) -> None: ...

    def list_by_aggregate(self, aggregate_type: str, aggregate_id: str) -> list[AuditRecord]: ...


class ScenarioRepository(Protocol):
    def list_scenarios(self, tenant_id: str = "tenant_demo") -> list[ScenarioSummary]: ...

    def get(self, scenario_id: str, tenant_id: str = "tenant_demo") -> object: ...


class ProcedureStore(Protocol):
    def save_definition(self, definition: ProcedureDefinition) -> None: ...

    def get_definition(self, procedure_id: str) -> ProcedureDefinition | None: ...

    def list_definitions(self) -> list[ProcedureDefinition]: ...

    def save_execution(self, execution: ProcedureExecution) -> None: ...

    def get_execution(self, execution_id: str) -> ProcedureExecution | None: ...

    def list_executions(self, procedure_id: str) -> list[ProcedureExecution]: ...


class ScenarioDefinitionStore(Protocol):
    def save(self, definition: ScenarioDefinition) -> None: ...

    def get(self, scenario_id: str) -> ScenarioDefinition | None: ...

    def list(self) -> list[ScenarioDefinition]: ...


class PersonaDefinitionStore(Protocol):
    def save(self, definition: PersonaDefinition) -> None: ...

    def get(self, persona_id: str) -> PersonaDefinition | None: ...

    def list(self) -> list[PersonaDefinition]: ...


class RuleStore(Protocol):
    def save(self, definition: RuleDefinition) -> None: ...

    def get(self, rule_id: str) -> RuleDefinition | None: ...

    def list(self) -> list[RuleDefinition]: ...
